### ISSUE TITLE
Insert "What's Major League Hacking?"

### ISSUE THREAD

**Issue by lanpaje** [IncubedSF/bhaveshc789.github.io#2]
<h5 class ="amber-text"> What's Major League Hacking?</h5>

 <p class ="white-text"> Major League Hacking (MLH) is the official student hackathon league. Each year, MLH powers over 200 weekend-long invention competitions that inspire innovation, cultivate communities and teach computer science skills to more than 65,000 students around the world. MLH is an engaged and passionate maker community, consisting of the next generation of technology leaders and entrepreneurs.</p>
 
</br></br>
          
 <p class ="white-text">SF Hacks is an official MLH Member Event. We follow the MLH<a class="amber-text" href="https://static.mlh.io/docs/mlh-code-of-conduct.pdf"><u> Code Of Conduct.</u></a>
You authorize us to share certain application/registration information for event administration, ranking, MLH administration, pre and post-event informational e-mails, and occasional messages about hackathons in line with the MLH <a class="amber-text" href="https://mlh.io/privacy"><u> Privacy Policy</u></p>

**Comment by Mahdi451** [comment]
Done and live!
