### ISSUE TITLE
Typeform Modification

### ISSUE THREAD

**Issue by lanpaje** [IncubedSF/bhaveshc789.github.io#3]
creates a typeform overlay on the website rather than opening a new webpage

<a class="typeform-share button" href="https://sfhacks1.typeform.com/to/NPTzRf" data-mode="1" target="_blank">Register Now</a>
<script>(function(){var qs,js,q,s,d=document,gi=d.getElementById,ce=d.createElement,gt=d.getElementsByTagName,id='typef_orm',b='https://s3-eu-west-1.amazonaws.com/share.typeform.com/';if(!gi.call(d,id)){js=ce.call(d,'script');js.id=id;js.src=b+'share.js';q=gt.call(d,'script')[0];q.parentNode.insertBefore(js,q)}id=id+'_';if(!gi.call(d,id)){qs=ce.call(d,'link');qs.rel='stylesheet';qs.id=id;qs.href=b+'share-button.css';s=gt.call(d,'head')[0];s.appendChild(qs,s)}})()</script>

**Comment by Mahdi451** [comment]
Need some more clarification as to what you want to do here, maybe make a pull request...

**Comment by Mahdi451** [comment]
I don't think this feature is really necessary, opening the typeform in a new tab is fine.
